openapi: 3.0.0
info:
  title: Portfolio CMS API
  version: 1.0.0
  
servers:
  - url: 'http://localhost:3000'
    description: Local development server
  
paths:
  /v1/auth/login:
    post:
      summary: Admin Login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              description: HttpOnly cookies (access + refresh token)
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login successful
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 64f1c2a9e1234567890abcd
                      username:
                        type: string
                        example: john_doe
                      email:
                        type: string
                        example: john@example.com
        '400':
          description: Invalid credentials or validation error
          content: 
            application/json:
              schema:
                $ref: '#/schemas/ErrorResponse'
        '404':
          description: User not found
          content: 
            application/json:
              schema:
                $ref: '#/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content: 
            application/json:
              schema:
                $ref: '#/schemas/ErrorResponse'
